name = "DyadicRealm"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["DyadicRealm"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0-rc1"

[[require]]
name = "leancert"
git = "https://github.com/alerad/leancert"
rev = "main"

[[lean_lib]]
name = "DyadicRealm"
